name: Lint Go code

on:
  push:
    branches:
      - main
      - go-codes


jobs:
   go-lint:
     name: lint
     runs-on: ubuntu-18.04
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
         with:
           go-version: '1.22'

      - name: golang-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: 1.58